version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  stary-serwis:
    image: stary-serwis:latest
    build:
      context: ./stary-serwis
    ports:
      - "8081:8080"
    depends_on:
      - kafka

  nowy-serwis:
    image: nowy-serwis:latest
    build:
      context: ./nowy-serwis
    ports:
      - "8080:8080"
    depends_on:
      - kafka
